/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package major;

import java.awt.BorderLayout;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Ruchi
 */
public class SoundSystemResultformCompany extends javax.swing.JFrame {
String brand1;
    /**
     * Creates new form MobileResultform
     */
    public SoundSystemResultformCompany(String s1,float ServiceAndSupportPolarity1,
            float FeaturesPolarity1,float MentionPolarity1,int totalpos,int totalneg,int totalneu,int deals) {
        brand1=s1;
       
        initComponents();
        
        BName1.setText(brand1);
       
        
        
        String SSString1 = String.format("%.04f",ServiceAndSupportPolarity1);
        SSPol1.setText(SSString1);
       
        String OFString1 = String.format("%.04f",FeaturesPolarity1);
        OFPol1.setText(OFString1);
        String MString1 = String.format("%.04f",MentionPolarity1);
        MPol1.setText(MString1);
        
        deals1.setText(""+deals);
       
     
        if(FeaturesPolarity1>0)
            jTextArea1.append("\n#Overall Features of " + brand1 + " are appreciated. \n   People tend to like the features.");
        else
            jTextArea1.append("\n#Overall Features of " + brand1 + " are not appreciated. \n  Efforts should be made to acheive maintain high sandards of features \n with competetive abilities");
        
        if(MentionPolarity1>0)
            jTextArea1.append("\n# " + brand1 + " has a good Electric Word of Mouth. \n   This can be used as a medium for online promotions");
        else
            jTextArea1.append("\n# " + brand1 + " suffers with Negative Electric Word of Mouth Measure. \n Consumers are dissatisfied with overall product.");;
                    
            
           
        if(ServiceAndSupportPolarity1>0)
            jTextArea1.append("\n#After purchase Services and Support of " + brand1 + "\n  are appreciated \n Indicative of good Customer-Management Relationship");
        else
            jTextArea1.append("\n#After purchase Services and Support of " + brand1 + "\n  are not appreciated which can serve as a reason for \n Customer defection");
        
       
         
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BName1 = new javax.swing.JTextField();
        OtherFeatures1 = new javax.swing.JLabel();
        Mention1 = new javax.swing.JLabel();
        ServiceAndSupport1 = new javax.swing.JLabel();
        OFPol1 = new javax.swing.JTextField();
        MPol1 = new javax.swing.JTextField();
        SSPol1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deals1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BName1.setEditable(false);
        BName1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BName1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BName1ActionPerformed(evt);
            }
        });

        OtherFeatures1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OtherFeatures1.setText("Features");

        Mention1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Mention1.setText("Mention");

        ServiceAndSupport1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ServiceAndSupport1.setText("Service And Support");

        OFPol1.setEditable(false);

        MPol1.setEditable(false);

        SSPol1.setEditable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("GENERATE BAR GRAPH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Deals");

        deals1.setEditable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\as\\Documents\\NetBeansProjects\\Major\\images\\bird_blue_48.png")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Vijaya", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Tweewomt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BName1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Mention1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MPol1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(OtherFeatures1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OFPol1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ServiceAndSupport1)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(deals1)
                                    .addComponent(SSPol1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OtherFeatures1)
                            .addComponent(OFPol1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Mention1)
                            .addComponent(MPol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ServiceAndSupport1)
                            .addComponent(SSPol1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(deals1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BName1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       /* DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
        barChartData.setValue(20,"Contibution","JAnuary");
        barChartData.setValue(10,"Contibution2","February");
         barChartData.setValue(30,"Contibution","March");
        
        JFreeChart barChart= ChartFactory.createBarChart("Contributions","Monthly","Contribution amount",barChartData,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot BarC=barChart.getCategoryPlot();
        BarC.setRangeGridlinePaint(Color.ORANGE);
        ChartPanel barPanel=new ChartPanel(barChart);
        //jPanel1.removeAll();
        jPanel1.add(barPanel);
        jPanel1.validate();
        //jPanel1.setVisible(true);
        */
  
       Scanner sc1 = null;
    try {
        sc1 = new Scanner(new File("DatasetCompany\\Week1 SoundSystem"+brand1+"Sentiments.txt"));
    } catch (FileNotFoundException e) {
        e.printStackTrace();  
    }
    int x1=0;
    int[] arr1=new int[3];
    while (sc1.hasNextLine()) {
            Scanner s1 = new Scanner(sc1.nextLine());
        while (s1.hasNext()) {
            String str1 = s1.next();
            x1++;
            if(x1%2==0)
            arr1[x1/2-1]= Integer.parseInt(str1);   
            System.out.println(str1);
        }
    }
    
          Scanner sc2 = null;
    try {
        sc2 = new Scanner(new File("DatasetCompany\\Week2 SoundSystem"+brand1+"Sentiments.txt"));
    } catch (FileNotFoundException e) {
        e.printStackTrace();  
    }
    int x2=0;
    int[] arr2=new int[3];
    while (sc2.hasNextLine()) {
            Scanner s2 = new Scanner(sc2.nextLine());
        while (s2.hasNext()) {
            String str2 = s2.next();
            x2++;
            if(x2%2==0)
            arr2[x2/2-1]= Integer.parseInt(str2);   
            System.out.println(str2);
        }
    }
    
    
     Scanner sc3 = null;
    try {
        sc3 = new Scanner(new File("DatasetCompany\\SoundSystem"+brand1+"Sentiments.txt"));
    } catch (FileNotFoundException e) {
        e.printStackTrace();  
    }
    int x3=0;
    int[] arr3=new int[3];
    while (sc3.hasNextLine()) {
            Scanner s3 = new Scanner(sc3.nextLine());
        while (s3.hasNext()) {
            String str3 = s3.next();
            x3++;
            if(x3%2==0)
            arr3[x3/2-1]= Integer.parseInt(str3);   
            System.out.println(str3);
        }
    }
    
    /*
    System.out.println(arr1[0]);
    System.out.println(arr1[1]);
    System.out.println(arr1[2]);*/
        CreateBarChart cc1=new CreateBarChart("MAJOR",brand1,arr1,arr2,arr3);
        cc1.pack();
        cc1.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        cc1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoundSystemResultformCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoundSystemResultformCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoundSystemResultformCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoundSystemResultformCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MobileResultformConsumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BName1;
    private javax.swing.JTextField MPol1;
    private javax.swing.JLabel Mention1;
    private javax.swing.JTextField OFPol1;
    private javax.swing.JLabel OtherFeatures1;
    private javax.swing.JTextField SSPol1;
    private javax.swing.JLabel ServiceAndSupport1;
    private javax.swing.JTextField deals1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
